name: Build and Upload Binaries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make fpc lazarus

      - name: Set LAZARUS_DIR environment variable
        run: echo "LAZARUS_DIR=/usr/lib/lazarus" >> $GITHUB_ENV

      - name: Build the application
        run: |
          lazbuild -B "transgui.lpi" --lazarusdir=$LAZARUS_DIR
          make
          make zipdist
        env:
          LAZARUS_DIR: ${{ env.LAZARUS_DIR }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: transgui-binaries
          path: Release/*.zip