name: Build and Upload Binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make fpc

      - name: Build the application
        run: |
          # Assuming there's a Makefile in the repo that compiles the Pascal code
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: transgui-binaries
          path: |
            build_folder/*.exe
            build_folder/*.dll
            build_folder/*.so
            build_folder/*.dmg
            build_folder/*.app